version: 2
plan:
  project-key: AN
  key: PLAN
  name: My Plan

stages:
  - Stage 1:
      jobs:
        - Job 1

Job 1:
  tasks:
    - script:
        - echo 'lets roll this again '
        - echo Hello
        - bash "chmod +x ../qualiti-script.sh"
        - bash "../qualiti-script.sh"
